addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.30")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"     % "2.4.16")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
